//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Stello.rc
//
#define IDD_ABOUTBOX                    100
#define IDD_ANALYSE                     101
#define IDP_SOCKETS_INIT_FAILED         104
#define IDR_MAINFRAME                   128
#define IDR_STELLOTYPE                  129
#define IDD_GAMETID                     130
#define IDC_EDIT1                       1000
#define IDC_EDIT2                       1002
#define IDC_EDIT3                       1003
#define IDC_EDIT4                       1004
#define IDC_EDIT5                       1005
#define IDC_SPILTID_OK                  1006
#define IDC_SPILTID_FORTRYD             1007
#define ID_NYT_SPIL                     32771
#define ID_ANALYSE                      32772
#define ID_SKIFT_SIDE                   32773
#define ID_SPIL_TID                     32774
#define ID_FREM                         32775
#define ID_TILBAGE                      32776
#define ID_TRAK_NU                      32777
#define ID_SPIL_FLETSPIL                32778
#define ID_MINMAXLIB                    32779
#define ID_SELFPLAY                     32780

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        131
#define _APS_NEXT_COMMAND_VALUE         32781
#define _APS_NEXT_CONTROL_VALUE         1008
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
