<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Stello.App\Stello.App.csproj" />
    <ProjectReference Include="..\Stello.Engine\Stello.Engine.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\Stello C++\OPENING" Link="Data\OPENING" CopyToOutputDirectory="PreserveNewest" />
    <Resource Include="..\Images\2026 Claus Pedersen.jpg" Link="Images\ClausPedersen.jpg" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Stello.Net.Tests" />
  </ItemGroup>

</Project>
